sudo: required
language: bash
services:
  - docker

before_script:
  - 
  - docker build . --tag=$APP_IMAGE
script:
  - docker run --rm --entrypoint '/bin/sh' $APP_IMAGE python3 -m pytest
after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true

  script: ./deploy.sh
  on:
    tags: true
