version: '3'
services:
  # for development purposes
  dev:
    build: .
    image: "pocin/kbc-processor-html2csv:dev"
    volumes:
        - ./:/code
        - ./data:/data
    command:
      - /bin/sh
