version: '3'
services:
  # for development purposes
  dev:
    build: .
    image: "pocin/kbc-processor-html2csv:dev"
    volumes:
        - ./:/code
        - ./tests/data/in/files/Transaction_Report.2018-03-06.xls:/data/in/files/report_test.xls
        - ./data/:/data/out/files/
    command:
      - /bin/sh
